### ISSUE TITLE
Request for a new event "ALL_FINISHED" and useAllFinishedListner-hook

### ISSUE THREAD

**Issue by LukasOchmann** [rpldy/react-uploady#123]
**Is your feature request related to a problem? Please describe.**
After all upload are done i want to show an Result, wich file got uploaded and wich did not. Currently only the first finished batch is Shown in my results.

**Describe the solution you'd like**
like the event ALL_ABORT an ALL_FINISCHED event and an correlated hook would be my preferred solution.
Triggered when the last pending batch is finished.

**Describe alternatives you've considered**
I am open for other solutions or a guide to do this

**Comment by yoavniran** [comment]
the difference with ALL_ABORT is that it is triggered as response to a specific action that happens once. While file uploading is asynchronous and therefore harder to pin down.
Since uploads can always be added to the uploader, it cannot really tell when uploading is done, so an ALL_FINISHED event makes less sense.

You can achieve a similar result with tracking BATCH_START and BATCH_FINISH in your own state

**Comment by LukasOchmann** [comment]
I will try to create an custom hook and will respond my results once i am finished.

**Comment by yoavniran** [comment]
closing for now.
