### ISSUE TITLE
useBatchAbortListener not triggerd when abortAll is executed

### ISSUE THREAD

**Issue by LukasOchmann** [rpldy/react-uploady#126]
**Describe the bug**
when the `abortAll` method returned from use `useAbortAll` is called, Listeners registered by `useBatchAbortListener` do not trigger

**To Reproduce**
See this Sandbox: https://codesandbox.io/s/empty-breeze-du608?file=/src/App.js
1. Click on 'Upload', choose a file.
2. Click on 'Go'
3. Click on 'Abort all'
4. In the Console, the click was detected. But the `console.log` from the `useBatchAbortListener` in the  `Noop`-component did not execute.

**Expected behavior**
 `useBatchAbortListner` for all aborted Batches are triggered.

**Versions**
@rpldy/mock-sender 0.9.0
@rpldy/sender 0.9.0
@rpldy/upload-button 0.9.0
@rpldy/uploader 0.9.0
@rpldy/uploady 0.9.0

**Code**
See sandbox above

**Comment by yoavniran** [comment]
Hi @LukasOchmann 
Specifically this isnt considered a bug because this behavior (or lack thereof) is by design. 
When abort all is used, all of the items are aborted, regardless of their batches. 

When I built it like this, I didnt consider a use-case where the respective batches abort event will be needed. 
As it is, I consider this an enhancement rather than a bug.

It would help if you could expand on your use-case and whether this event is really needed or can the required functionality be achieved by other means.

**Comment by LukasOchmann** [comment]
Hi @yoavniran 
thanks for Clarifying. 

I found an other way, so i guess this issue can be closed.

**Comment by yoavniran** [comment]
Great. If you like, you can add your solution in the [discussions](https://github.com/rpldy/react-uploady/discussions) section for others to learn from.
Thanks!
