### ISSUE TITLE
Retry doesnt "remember" SendOptions 

### ISSUE THREAD

**Issue by yoavniran** [rpldy/react-uploady#447]
based on #442

**Comment by yoavniran** [comment]
@Tekpakma If you can, please add more info about this issue and if possible provide reproduction code/details

**Comment by Tekpakma** [comment]
So i checked the problem out a bit. The "problem" is, that for resuming uploads, Tus sends a HEAD request to the server. But it ignores any Header set (Which propably only matters for Authorization Headers). This is because in the tus-sender package, the head request is created like this:
 const pXhr = request(url, null, {
    method: "HEAD",
    headers: {
      "tus-resumable": options.version
    }
  });
  and only uses the url from localStorage.
![Pic1](https://user-images.githubusercontent.com/73849736/213492262-301c9104-032e-4f48-b9f2-46fe96c51fa9.jpeg)
![Pic2](https://user-images.githubusercontent.com/73849736/213492318-2609d54c-9e92-4b97-83fe-739d6010ded1.jpeg)

**Comment by yoavniran** [comment]
Very interesting, thanks!
So probably will be good to have an optional resumeHeaders property that will be used in cases like this. 
How does that sound?

**Comment by Tekpakma** [comment]
> 

Sounds good!
