### ISSUE TITLE
Unexpected deletion of uploading images when trying to retry

### ISSUE THREAD

**Issue by omcg33** [rpldy/react-uploady#83]
I abort and retry items in batch of 7 items, and got this error

```
batchHelpers.js:13 Uncaught (in promise) TypeError: Cannot read property 'batch' of undefined
    at getBatchFromState (batchHelpers.js:13)
    at triggerUploaderBatchEvent (batchHelpers.js:106)
    at cleanUpFinishedBatch (batchHelpers.js:98)
    at processFinishedRequest.js:65
    at processBatchItems.js:94
```
And all my not uploaded items is disappeared!

Steps to reproduce:

1. Slow network speed
2. Upload 10 items in 1 batch on multiply
3. Abort and retry all of items step by step
4. Wait then about 20% of items will be uploaded
5. Items disappeared and you got error

**Comment by yoavniran** [comment]
I've tried reproducing the issue using this [story](https://react-uploady-storybook.netlify.app/?path=/story/retry-hooks--with-retry-and-preview) and wasnt able to.
Im also surprised that it threw this error (with that stacktrace) because it means something weird happened with the internal state.

I am adding a [conditional](https://github.com/rpldy/react-uploady/commit/33bec1ed098d35146a525be2cc306b25d7c5c10a#diff-a4a25462178b8b010b4d8951997d2ac8R105) so this error shouldnt happen in the future. But again, Im surprised that it did in the first place.

If you can share more of your code so i can better understand how this happened that could help.


Also, I dont understand what you mean by:

> And all my not uploaded items is disappeared!

Please explain. 
I will just note that you shouldnt rely on the uploader's internal state for building your UI. Uploady will clean up its internal store agressively to maintain the smallest memory footprint possible.

**Comment by yoavniran** [comment]
@omcg33 version 0.7.0 is out.
please let me know if you're still facing issues after upgrading
